config/routes.rb
Rails.application.routes.draw do
  get 'survivals/apocalypse'

  get 'survival/apocalypse'

  root to: 'survivals#index'

  get "apocalypse", to: 'home#index'

  resources :survivals
  resources :resources
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/survival.rb
class Survival < ApplicationRecord
  enum situation: [:alive, :infected]

  scope :non_infected, -> {where(situation: :alive)}
  scope :infected, -> {where(situation: :infected)}

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < SurvivalsController
  def index
    @survival_total = Survival.all.size.to_i
    @non_infected = Survival.where(situation: :non_infected).size.to_i
    @infected = Survival.where(situation: :infected).size.to_i
    water = 0
    food = 0
    medication = 0
    ammunation = 0
    survivors = Survival.all

    survivors.each do |survivor|
      water = water + survivor.resource1.to_i
      food = food + survivor.resource2.to_i
      medication = medication + survivor.resource3.to_i
      ammunation = ammunation + survivor.resource4.to_i
    end

    @water = water/@survival_total.to_f
    @food = food/@survival_total.to_f
    @medication = medication/@survival_total.to_f
    @ammunation = ammunation/@survival_total.to_f

  end

  def info
    msg = { non_infected: @non_infected, infected: @infected, water: @water, food: @food, medication: @medication, ammunation: @ammunation}
    render json: msg
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:description, :points)
    end
end

app/controllers/survivals_controller.rb
class SurvivalsController < ApplicationController
  before_action :set_survival, only: [:show, :edit, :update, :destroy]

  # GET /survivals
  # GET /survivals.json
  def index
    @survivals = Survival.all
    if params[:search]
      @survivals = Survival.search(params[:search])
    else
      @survivals = Survival.all
    end
  end

  # GET /survivals/1
  # GET /survivals/1.json
  def show
  end

  # GET /survivals/new
  def new
    @survival = Survival.new
  end

  # GET /survivals/1/edit
  def edit
  end

  # Survival /survivals
  # POST /survivals.json
  def create
    @survival = Survival.new(survival_params)

    respond_to do |format|
      if @survival.save
        format.html { redirect_to @survival, notice: 'Survival was successfully created.' }
        format.json { render :show, situation: :created, location: @survival }
      else
        format.html { render :new }
        format.json { render json: @survival.errors, situation: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survivals/1
  # PATCH/PUT /survivals/1.json
  def update
    respond_to do |format|
      if @survival.update(survival_params)
        format.html { redirect_to @survival, notice: 'Survival was successfully updated.' }
        format.json { render :show, status: :ok, location: @survival }
      else
        format.html { render :edit }
        format.json { render json: @survival.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survivals/1
  # DELETE /survivals/1.json
  def destroy
    @survival.destroy
    respond_to do |format|
      format.html { redirect_to survivals_url, notice: 'Survival was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survival
      @survival = Survival.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survival_params
      params.require(:survival).permit(:name, :year_birthday, :situation, :latitude, :longitude, :resource1, :resource2, :resource3, :resource4)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/survival_helper.rb
module SurvivalHelper
end

app/helpers/survivals_helper.rb
module SurvivalsHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="row jumbotron">
    <div class="row">
      <h2>Informations about our Community</h2>
      <div class="col-lg-6">
        <fieldset>
          <legend>People Alive</legend>
          <%= @non_infected %> of <%= @survival_total %>
        </fieldset>
      </div>
      <div class="col-lg-6">
        <fieldset>
          <legend>People infected</legend>
          <%= @infected %> of <%= @survival_total %>
        </fieldset>
      </div>
    </div>
  </div>

  <div class="row jumbotron d-block">
    <h2>Average of survivor's gear</h2>
    <div class="col-lg-6">
      <legend>Water</legend>
        <%= @water %>
      </fieldset>
    </div>
    <div class="col-lg-6">
      <fieldset>
        <legend>Food</legend>
        <%= @food %>
      </fieldset>
    </div>
    <div class="col-lg-6">
      <fieldset>
        <legend>Medication</legend>
        <%= @medication %>
      </fieldset>
    </div>
    <div class="col-lg-6">
      <fieldset>
        <legend>Ammunation</legend>
        <%= @ammunation %>
      </fieldset>
    </div>
  </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zombie Survival</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= image_tag "hand.png", size: "30x30", style: "padding-right: 5px"%>
  <a class="navbar-brand" href="#">Zombie Survival</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Survivals", survivals_path, class: "nav-link" %>
      <%= link_to "Trade", "#", class: "nav-link", disable: true %>
      <%= link_to "Apocalypse Info", apocalypse_path, class: "nav-link" %>
    </div>
  </div>
  <div class="form-inlinm-2 my-lg-0y e">
    <%= form_tag(survivals_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search survivals" %>
    <%= submit_tag "Search" %>
    <% end %>
  </div>
</nav>
<div class="container">
  <%= image_tag "header2.png", class: "img-fluid" %>
</div>
<%= yield %>
</body>
</html>

app/views/resources/_form.html.erb
<%= form_with(model: resource, local: true) do |form| %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :resource_description %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points, id: :resource_points %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resources</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.description %></td>
        <td><%= resource.points %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form', resource: @resource %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Points:</strong>
  <%= @resource.points %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/survivals/_form.html.erb
<div class="container">

  <%= form_with(model: survival, local: true) do |form| %>
  <% if survival.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(survival.errors.count, "error") %> prohibited this survival from being saved:</h2>

    <ul>
      <% survival.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="form-field">
          <%= form.label :name %>
          <%= form.text_field :name, id: :survival_name, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label :year_birthday %>
          <%= form.number_field :year_birthday, id: :survival_year_birthday, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label :gender %>
          <%= form.text_field :gender, id: :survival_name, class: "form-control", placeholder: "F to female/ M to male" %>
        </div>

        <div class="form-field">
          <%= form.label :situation %>
          <%= form.text_field :situation, id: :survival_situation, class: "form-control", placeholder: "alive or infected", value: ("0").to_i %>
        </div>

        <div class="form-field">
          <%= form.label :latitude %>
          <%= form.text_field :latitude, id: :survival_latitude, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label :longitude %>
          <%= form.text_field :longitude, id: :survival_longitude, class: "form-control" %>
        </div>
      </div>

      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="jumbotron">
        <p>Please, set the value of your resources that you possess</p>
        <div class="form-field">
          <%= form.label "water" %>
          <%= form.number_field :resource1, id: :survival_resource1, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label "food" %>
          <%= form.number_field :resource2, id: :survival_resource2, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label "medication" %>
          <%= form.number_field :resource3, id: :survival_resource3, class: "form-control" %>
        </div>

        <div class="form-field">
          <%= form.label "ammunation" %>
          <%= form.number_field :resource4, id: :survival_resource4, class: "form-control" %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/survivals/edit.html.erb
<div class="container">

  <%= form_with(model: @survival, local: true) do |form| %>
  <% if @survival.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(survival.errors.count, "error") %> prohibited this survival from being saved:</h2>

    <ul>
      <% survival.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :survival_name, class: "form-control", disabled: true   %>
  </div>

  <div class="form-field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :survival_latitude, class: "form-control" %>
  </div>

  <div class="form-field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :survival_longitude, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>
</div>

<%= link_to 'Show', @survival %> |
<%= link_to 'Back', survivals_path %>

app/views/survivals/index.html.erb
<div class="container">

<p id="notice"><%= notice %></p>

<h1>Survivals</h1>

<%= link_to 'New Survival', new_survival_path, class: "btn btn-info" %>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Situation</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @survivals.each do |survival| %>
      <% if survival.situation != "alive" %>
      <tr style="color: #fff; background: #f00;">
        <td><%= survival.name %></td>
        <td><%= survival.situation %></td>
        <td><%= link_to 'Show', survival %></td>
        <td><%= link_to 'Edit', edit_survival_path(survival) %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= survival.name %></td>
        <td><%= survival.situation %></td>
        <td><%= link_to 'Show', survival %></td>
        <td><%= link_to 'Edit', edit_survival_path(survival) %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/survivals/new.html.erb
<%= render 'form', survival: @survival %>

<%= link_to 'Back', survivals_path %>

app/views/survivals/search.html.erb
<div class="container">
  <%= form_tag survival_path, :method => 'get'  do %>
  <%= text_field_tag :search, params[:search]%>
  <%= submit_tag "Search", :name => nil  %>
<% end %>
</div>

app/views/survivals/show.html.erb
<div class="container">
<div class="jumbotron">

<p id="notice"><%= notice %></p>
<div class="col-md-6">

<% x = Time.current.year - @survival.year_birthday %>

<h3><strong><%= @survival.name %>, age <%= x %></strong></h3>
<% if @survival.gender = "m" %>
  <p>
    <label>Gender:</label>
    Male
  </p>
<% else %>
  <p>
    <label>Gender:</label>
    Female
  </p>
<% end %>
<p>
  <label>Situation:</label>
  <%= @survival.situation %>
</p>
<p>
  <label>Latitude:</label>
  <%= @survival.latitude %>
</p>

<p>
  <label>Longitude:</label>
  <%= @survival.longitude %>
</p>

<p>
  <label>Water:</label>
  <%= @survival.resource1 %>
</p>

<p>
  <label>Food:</label>
  <%= @survival.resource2 %>
</p>

<p>
  <label>Medication:</label>
  <%= @survival.resource3 %>
</p>

<p>
  <label>Ammunation:</label>
  <%= @survival.resource4 %>
</p>

<%= link_to 'Edit', edit_survival_path(@survival) %> |
<%= link_to 'Back', survivals_path %>

</div>
</div>